server:
  error:
    include-exception: true
    include-stacktrace: always
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  rooturl: '/'
  profiles:
    active: default

  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

    async:
      request-timeout: 600000

  thymeleaf:
    view-names: thymeleaf/*
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

  session:
    timeout: 3600
    store-type: redis
    redis:
      flush-mode: on_save

  #local settings
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
      file-size-threshold: 500MB
      location: C:/project/Temp

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/practice?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true
      pool-name: hikari-cp
      maximum-pool-size: 5
      username: root
      password: 1q2w3e4r%
      driver-class-name: com.mysql.cj.jdbc.Driver
      auto-commit: false

logging:
  level:
    root: debug
    org.springframework: warn
    io.lettuce: warn
  file:
    name: practice.log
    max-size: 100MB
    path: './logs'